[package]
name = "component-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
inquire = "0.7.5"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"